# Creation of the Book
## Group Process Documentation
Our Team Charter has been our Holy Grail to keep our meetings, accountability, and deadlines in check. Most of our communication is hosted on GroupMe where we set up our time to meet during the weeks to work on the website. During these meetings, most of our brainstorming happens, and we capitalize using the resources at Ross like the Study Rooms, common screens, and the white boards to bounce off a lot of ideas and gradually converge our focus and work towards that. We usually start the meetings by discussing what we learned in the class before and how we can use any relevant topics to incorporate in our work product. More specifically, we write down keywords during these brainstorming sessions so that we can refer back to them to build up our book using the topics taught in the class.

One class resource that we heavily utilized to improve our guide was the user stories. We identified our main users as incoming Ross MBAn students. So, to conduct these user interviews, we asked our interviewees to answer our questions from the perspective of an incoming MBAn student (luckily, they were in this position just one month before) and identify the main areas of housing & move-in, academics, student resources, shopping, commuting, etc. that they felt they needed more information on and what they thought would be useful for us to include in our guide. Interviewing two classmates on their experiences in Ann Arbor (AA) thus far and what they would want out of our guide helped us to understand which topics were important to cover and how we can present that information to be most useful to our users. One student that we interviewed grew up an hour away from AA and went to undergrad here, whereas the other had never been here before. So, we were able to gain insights from a wide range of perspectives and learn how we can help those who are brand new to AA and those who are looking to dive deeper beyond what they already knew about AA. 

## Handling Challenges and Change
Due to our informal bonding during the beginning of our meet-ups, our group developed a high cohesion and group understanding. In face of any challenges and change, we found ourselves to be accommodating and flexible to make the most out of changing situations / challenging circumstances. Our greatest strength as a team is our ability to have empathy for one another. For example, when team members had health complications, other members had no hesitation stepping up to take on more work. When challenges arise, our team is efficient in finding solutions. We listen and build off each other's rhetoric to overcome challenges and come out even stronger.

## Division of Work and Leveraging Strengths
We divided most of our work based on our experiences within Ann Arbor. As an international student, Yuqi had a lot of ideas for move-in and how to get to Ann Arbor. Kian had recently gone through the process of getting car insurance and dealing with transportation. Raj is very fashion forward, so he had a lot of insight for shopping. Rory had been in Ann Arbor for undergrad, so she knew a lot about the local restaurants and bars. Kami also was here for undergrad, so she was keen to the resources offered to students. We all chose to write about something that we really understood and I think that was how we really leveraged our strengths. 

## Agile Work Practice
One of our favorite agile principles is "the most efficient and effective method of conveying information to and within a development team is face-to-face conversation." Our group makes a conscious effort to meet in-person so that we can hangout a little bit, see how everyone is doing before getting to work. This has helped our team bond a lot and become more effective towards our goal. We have  discussed everything from cars, songs, vacation plans etc. and it has made us relate to each other a lot. This understanding has translated into accountability where everyone honors internal deadlines and promotes a glass house environment where we are not afraid to ask for help from each other. Another Agile practice that we have capitalized is the idea of "Iterative, incremental, evolutionary." We make changes to our book often, add useful information as and when we deem useful, and seek feedback from within the group and from our peers to make it more useful to our audience.

## RMarkdown/Git/GitHub
The technical aspect of the project impacted each of us differently due to our backgrounds and previous knowledge of using a coding language and a platform like GitHub. In face of ambiguity and initial setup, Google was our go-to resource beside each other. We relied on each other to impart a common, incremental understanding of R and Git within the group so everyone is comfortable and proficient enough to use the platforms independently and confident enough to seek help from each other. For example, we went through the R concepts collectively before the first R submission. In order to complete the "About Me" activity we made sure that everyone pushed their content individually so that each of us had the R setup with necessary packages installed.

## Becoming a More Effective and Productive Team
Over the course of the semester, our team has had steady progress in developing our team bonding and trust. Watching our team grow, not just as students, but also as friends, has been a great experience and has set a precedent for our respective teams in the future. We strive to become an even more effective team with each meeting. Thus, our productivity and creativity of ideas have increased as well. For example, during one meeting, we all showed pictures of our dream cars before formally starting the team meeting. This small fifteen minute gesture helped form better relationships within our team and increased our trust. This example is just one of the many short activities we participate in to psychological safety in the group and become more effective as a team. Even now, as we are wrapping up our semester and making final touches on our semester-long project, our group still emphasizes the importance of building interpersonal relationships for continuous team growth. 




