# Academics {#academics}

## Orientation

Orientation will take place some point in late June and will be an introduction to the Ross School of Business and the University of Michigan as a whole. It will be four days long and will consist of workshops, team bonding activities, and informational sessions.

## What to Expect from Summer Classes

The summer classes serve as an introduction to business and the classes you will be taking in the future.

## Summer Career Opportunities

The [Career Development Office](https://sites.google.com/umich.edu/cdo-specialtymasters/home) will be your source of information for all things career. They can help you with things like recruiting, resume building, networking, interview prep, and more.

Your program will have their own dedicated career coach to help you with all these things. You can make meetings with them to answer any questions you have, get feedback on your resume, or chat about potential career opportunities. 

There will also be several career building sessions throughout the summer that you can attend. Some of them might be required for one of your courses. These sessions cover a range of topics, including but not limited to:

* Two Hour Job Search
* Career Ingredients
* Resume
* LinkedIn
* Interview Storytelling