# Commuting Around Campus and Ann Arbor {#commuting}

## Walking
a.	Safety posts along the streets allow you to get instant direct contact with security
b.	Campus integrated with Ann Arbor streets for more organized travel
c.	https://maps.studentlife.umich.edu/

## Blue Buses
a.	Free with M Card
b.	Track bus routes in real time on the Magic Bus Website
c.	https://mbus.ltp.umich.edu/home

## The Ride
a.	Cheap and easy to travel between cities within Michigan
b.	https://www.theride.org/

## Cars/Parking
a.	Parking Passes
  i.	4 Tiers of passes available for faculty, students, and staff based on seniority
    1.	Gold, Blue, Yellow, Orange
  ii.	Graduate students are eligible for 4 types of parking permits with annual costs
    1.	Yellow/After Hours – $237
    2.	Student Storage – $234
    3.	Orange – $84
    4.	After Hours – $70 
  iii.	https://ltp.umich.edu/parking/permit-parking/
b.	Michigan Car Insurance
  i.	Michigan is considered a “no-fault” which makes insurance rates in the state significantly higher than average 
  ii.	https://www.michigan.gov/-/media/Project/Websites/autoinsurance/PDFs/FIS-PUB_0202a.pdf?rev=f0fb2628817f479d92ec040006bae492
c.	Plate and License Transition
  i.	https://www.secstates.com/MI_DMV_Michigan_Department_of_Motor_Vehicles

## SPIN Scooters
a.	Download the app on iOS or Android for a fun way to zip around campus

