# Shopping {#shopping}

One-stop shopping information website: https://www.annarbor.org/things-to-do/shopping/ 

Three broad sections of shopping in Ann Arbor

* Mall for mainstream and global shopping
* Local shop and boutiques around campus
* Historic neighborhoods for special items

## Mall
* Nearest mall is Briarwood Mall
    + 7 minutes drive from the Ross School of Business
    + Three anchor stores: Macy’s, JCPenny, and Von Maur
    + Hosts the only Apple Store in Ann Arbor
    + Variety of food options as well
        - Has a Cinnabon store as well which is must-try
        - Other options include Panda Express
  + https://www.simon.com/mall/briarwood-mall 

## Local Shops
* Nickels Arcade: shopping corridor near The State Theater with specialty retail stores   
    + Has boutique shops like Van Boven where you can buy clothing, accessories, footwear etc.
    + A-1 Alterations for your alternation and zipper repair needs 
        - Owners speak English and Mandarin Chinese
    + https://www.annarbor.org/listing/nickels-arcade/1108/ 
* Downtown
    + The Main Street is replete with shops selling anything antiques, plants, holiday gifts, authentic fossils and much more!
    + https://mainstreetannarbor.org/holiday-shopping-guide-1 

## Food 
* Kerrytown District: home to Ann Arbor’s farmer market and other local produces
    + Farmers Market: Wednesdays and Saturdays from 7am-3pm (May-December); Saturdays from 8 am-3 pm (January-April).
    + https://www.a2gov.org/departments/Parks-Recreation/parks-places/farmers-market/Pages/default.aspx
    + http://kerrytowndistrict.org/food-drinks-grocery 
* Chain stores: Meijer, Kroger, and Plum Market within 10 min driving distance. Target store next to The State Theater. Doordash and online delivery options available. Busch’s Fresh Food Market on S State St. 